import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import styles from "../styles/Home.module.css";
import { useState } from "react";
import moment from "moment";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [currentChat, setCurrentChat] = useState("");
  const [colorToggle, setColorToggle] = useState(false);
  const [chats, setChats] = useState([
    {
      message:
        "Lorem ipsum dolor sit amet consectetur adipisicing elit. Reprehenderit quibusdam aperiam repellendus fugiat itaque explicabo, quas distinctio tenetur aliquam atque.",
      time: "January 30,2023",
      color: "blue",
    },
    {
      message: "Answer in Lorem Ipsum blah blah blah",
      time: "January 30,2023",
      color: "gray",
    },
  ]);
  const addChat = (chat) => {
    let color = "gray";
    setCurrentChat("");
    setColorToggle((prev) => !prev);
    if (!colorToggle) {
      color = "blue";
    }

    console.log(chat, currentChat);
    const newMessage = {
      message: chat,
      time: moment().format("MMMM Do YYYY, h:mm:ss a"),
      color,
    };
    chats.push(newMessage);
  };
  // useEffect(() => {

  // }, [currentChat])

  return (
    <>
      <Head>
        <title>Chat App </title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/Sollet-Logo.png" />
      </Head>
      <main className="p-5 relative h-screen">
        <h1 className="font-semibold text-2xl">Question & Answers</h1>
        <hr className="mb-5" />
        <div className=" bg-red-200 ">
          {chats.map((x, key) => {
            return (
              <>
                <div
                  key={key}
                  className={`mb-2 ${
                    x.color == "blue"
                      ? "relative float-right "
                      : "relative float-left w-[50%]"
                  }`}
                >
                  <div
                    className={`${
                      x.color == "blue"
                        ? "bg-blue-600 text-white"
                        : "bg-gray-200 "
                    } p-2 rounded-lg`}
                  >
                    <p>{x.message}</p>
                  </div>
                  <small className="font-medium text-gray-400 text-end w-full">
                    {x.time}
                  </small>
                </div>
              </>
            );
          })}
        </div>
        {/* Chat Section */}
        <form
          onSubmit={(e) => {
            e.preventDefault();
            if (currentChat == "") return;
            addChat(currentChat);
          }}
        >
          <div className="w-full p-5 items-end justify-end absolute left-0 mb-5 bottom-0">
            <div className="flex gap-5">
              <input
                type="text"
                value={currentChat}
                onChange={(e) => setCurrentChat(e.target.value)}
                placeholder="Ask a Question"
                className="border-2 border-gray-300  rounded-lg p-3 w-[90%]"
              />
              <button
                className="bg-blue-500 p-3 rounded-md w-[10%] text-white font-semibold"
                onClick={() => {
                  if (currentChat == "") return;
                  addChat(currentChat);
                }}
              >
                Ask Question
              </button>
            </div>
          </div>
        </form>
      </main>
    </>
  );
}
